name: bloctest
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bloc: ^5.0.0
  hydrated_bloc: ^5.0.0
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  build_runner: ^1.10.0
  flutter_bloc: ^5.0.0
  path_provider: ^1.6.11


# dev_dependencies:

flutter:
  uses-material-design: true